// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdVIrSY5K2iSdI9oBih0UrUXjhbVKHkVk',
    appId: '1:9836645314:web:f8e5aed93d687ac423e45b',
    messagingSenderId: '9836645314',
    projectId: 'git-fit-3cf15',
    authDomain: 'git-fit-3cf15.firebaseapp.com',
    databaseURL: 'https://git-fit-3cf15-default-rtdb.firebaseio.com',
    storageBucket: 'git-fit-3cf15.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhNRRMgw2PxunKYUAbeTWu0A-tDLRydFo',
    appId: '1:9836645314:android:2acce6e05fcea44323e45b',
    messagingSenderId: '9836645314',
    projectId: 'git-fit-3cf15',
    databaseURL: 'https://git-fit-3cf15-default-rtdb.firebaseio.com',
    storageBucket: 'git-fit-3cf15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx3-DBs4ygLweYC1QXca4FklNVp3sLwHI',
    appId: '1:9836645314:ios:eabb76213a56cd9f23e45b',
    messagingSenderId: '9836645314',
    projectId: 'git-fit-3cf15',
    databaseURL: 'https://git-fit-3cf15-default-rtdb.firebaseio.com',
    storageBucket: 'git-fit-3cf15.appspot.com',
    iosBundleId: 'com.example.gitFit',
  );
}
